### ISSUE TITLE
Questions about using the cell centered composite solver for all amr levels

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/EBIAMR#1]
Hello all,

**I want to use the cell center composite solver to solve the Poisson equation among all amr levels, which kinds of solvers under the directory /linear solvers in the amrex package?**

I knew that IAMR used the node center composite solver to solve the Poisson equation among all amr levels at the initialization process. I also noticed that there is a new released MLMG solver.  In the release notes, it says this solver is used to solve for mac projection, mac sync solves, and scalar diffusion, yet all these three steps are level solvers according to the paper. But from the name "MLMG", I guessed it refers to the "Multi Level Multi Grid" solver, so I am confused whether I can use this solver. 

Thanks so much.

Best.

Ruohai

**Comment by WeiqunZhang** [comment]
This is really an AMReX question.  If you post it there, I will answer it there.  Other people might have the same question.

**Comment by ruihai0925** [comment]
Sure @WeiqunZhang , thanks so much.
