### ISSUE TITLE
Questions about the FORT_PRESFILL subroutine in the PROB_2D.F

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/EBIAMR#2]
Hello everyone,

Here is a small question about the FORT_PRESFILL subroutine. To my understandings, only for some specific boundary conditions, should we use this subroutine to fill the outside patch which accords to the given physical boundary condition. 

Yet, it seems that in this subroutine, pressure boundary conditions in all sides are Neumann Boundary condition. I mean, if p(i,j) = p(ilo,j) and only one ghost cell is given, it seems to mean the derivative of pressure on the boundary is 0. **How about the Dirichlet boundary condition about pressure?**

Again, thanks for replying and I really appreciate it.

Best

Ruohai

**Comment by WeiqunZhang** [comment]
EBIAMR was created for development.  And this repo may be highly unstable.  So you should use IAMR instead.
